const terminal = document.getElementById("terminal");
const input = document.getElementById("commandInput");
const form = document.getElementById("commandForm");
const engine = new GalileoCommandEngine();
function print(text, kind = "") { const element = document.createElement("pre"); element.className = `output ${kind}`; element.textContent = text; terminal.appendChild(element); terminal.scrollTop = terminal.scrollHeight; }
function promptEcho(command) { print(`*${command}`, "dim"); }
function mark() { const state = engine.state; GalileoSteps.forEach(step => { const element = document.querySelector(`[data-step="${step}"]`); if (!element) return; const complete = { login: state.signedIn, availability: state.availability, sell: Boolean(state.segment), name: Boolean(state.name), contact: Boolean(state.phone), save: state.saved, price: state.priced, issue: state.issued }[step]; element.classList.toggle("done", complete); }); }
function update() { const state = engine.state; document.getElementById("sessionStatus").textContent = state.signedIn ? "SIGNED IN" : "OFFLINE"; document.getElementById("officeLabel").textContent = state.signedIn ? "OFFICE: DACVS01" : "OFFICE: --"; document.getElementById("locatorBadge").textContent = state.locator || "---"; const summary = document.getElementById("pnrSummary"); if (!state.locator && !state.segment && !state.name) summary.textContent = "No active booking"; else summary.innerHTML = `<b>${state.locator || "UNSAVED"}</b><br>${state.name || "Passenger not added"}<br>${state.segment ? `${state.segment.carrier}${state.segment.number} ${state.segment.origin}-${state.segment.destination}` : "No segment"}<br>${state.priced ? "FARE QUOTED" : "Not priced"}${state.issued ? "<br><b class='issued'>TICKET ISSUED</b>" : ""}`; mark(); }
function reset() { engine.reset(); terminal.innerHTML = ""; print("GELLELIO GALILEO TRAINING SIMULATOR\nTRAINING ENVIRONMENT - OFFLINE PRACTICE"); print("Type SON/DEMO/DEMO to sign in. Type HELP for available commands.", "dim"); update(); input.focus(); }
function process(raw) { const command = raw.trim(); if (!command) return; promptEcho(command); if (command.toUpperCase().startsWith("LESSON ")) { const lesson = GalileoLessons.get(command.slice(7)); if (lesson) print(GalileoLessons.format(lesson).join("\n"), "dim"); else print("LESSON NOT FOUND - USE BASIC, TICKETING OR MODIFICATION", "error"); update(); return; } const response = engine.process(command); if (response.lines.length) print(response.lines.join("\n"), response.kind || ""); update(); }
form.addEventListener("submit", event => { event.preventDefault(); process(input.value); input.value = ""; });
input.addEventListener("keydown", event => { if (event.key === "ArrowUp" && engine.state.history.length) input.value = engine.state.history[engine.state.history.length - 1]; });
window.reset = reset;
reset();
